### ISSUE TITLE
CPM: Identify the top list of primary methods that could be useful in controlling the CPM to complete the challenges

### ISSUE THREAD

**Issue by rbtgagnon** [frc-88/2020-Robot#3]
Some examples could be
Reset CPM
Deploy CPM
Retract CPM
Get current color under robot's sensor
Get current color under CPM field sensor
Rotate wheel clockwise ( some number of units) 
Rotate wheel counter-clockwise (some number of units) 
Stop wheel rotation

**Comment by nix342** [comment]
Some thoughts:
- "Get current color under CPM field sensor" - "Get" feels wrong as we don't have direct access to determine that value. "Calculate" seems more accurate as we would need to infer the color under the field sensor based on information we do know (color our sensor is detecting, positioning of the CPM and robot, etc).
- One additional method would be "Rotate wheel to target" which is really a combination of most of the others to do the "Position Control" action as quickly as possible (determine our color, determine the fastest way to more to the target color, rotate in the correct direction by the necessary amount, and the stop the wheel.

**Comment by nix342** [comment]
Discussed with team on 1/18.
